import * as _Array from "./array";
import * as _Collections from "./collections";
import * as _Object from "./object";
import * as _Pipe from "./pipe";
import * as _Promise from "./promise";
import * as _String from "./string";
import * as _Dispatcher from "./dispatcher";
import * as _Emitter from "./emitter";
import * as _Error from "./error";
import * as _Function from "./function";
export declare const _: {
    array: typeof _Array;
    collections: typeof _Collections;
    object: typeof _Object;
    pipe: typeof _Pipe;
    promise: typeof _Promise;
    string: typeof _String;
    dispatcher: typeof _Dispatcher;
    emitter: typeof _Emitter;
    error: typeof _Error;
    function: typeof _Function;
};
