export declare function createElement<T extends ChildNode = ChildNode>(template: string): T;
export declare function createElements<T extends Array<ChildNode> = Array<ChildNode>>(template: string): T;
export declare function createDocument(template: string): Document;
export declare function removeChildren($el: Element): void;
export * from "./audio";
export * from "./canvas";
export * from "./download";
export * from "./file";
export * from "./image";
export * from "./net";
export * from "./raf";
export * from "./video";
